name: Lint and Format

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: ['20.x']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: |
        echo "::group::ESLint Check"
        if ! npm run lint; then
          echo "::error::ESLint found issues. Run 'npm run lint:fix' to auto-fix some issues."
          echo "::notice::To fix ESLint issues, run: npm run lint:fix"
          exit 1
        fi
        echo "::endgroup::"

    - name: Check Prettier formatting
      run: |
        echo "::group::Prettier Check"
        if ! npm run format:check; then
          echo "::error::Code is not properly formatted. Run 'npm run format' to fix formatting issues."
          echo "::notice::To fix formatting issues, run: npm run format"
          exit 1
        fi
        echo "::endgroup::"

    - name: Success notification
      if: success()
      run: |
        echo "✅ All linting and formatting checks passed!"
        echo "::notice::Code quality checks completed successfully."